version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: api-gateway-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=apigw
    networks:
      - api-gateway-network

  # Redis service
  redis:
    image: redis/redis-stack:latest
    container_name: api-gateway-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - api-gateway-network

  # Node.js Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: api-gateway-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongodb:27017/api-gateway
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NEWS_API_KEY=80aedff7eaf44c60ba613d77129176c7
      - NEWS_API_BASE_URL= https://newsapi.org
    depends_on:
      - mongodb
      - redis
    networks:
      - api-gateway-network

volumes:
  mongodb_data:
  redis_data:

networks:
  api-gateway-network:
    driver: bridge
